# Generated by Django 5.1.7 on 2025-05-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petLikeFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petLikeFrom', to='pets.pet')),
                ('petLikeTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petLikeTo', to='pets.pet')),
            ],
        ),
    ]
