# Generated by Django 5.1.7 on 2025-05-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petDislikeFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_given', to='pets.pet')),
                ('petDislikeTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_received', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Sympathy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet1', to='pets.pet')),
                ('pet2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet2', to='pets.pet')),
            ],
        ),
    ]
