# Generated by Django 5.1.7 on 2025-03-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_premium_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(default=380111111111),
            preserve_default=False,
        ),
    ]
